"""empty message

Revision ID: 92614fe1f829
Revises: 
Create Date: 2020-02-18 09:18:42.298356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92614fe1f829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
